import HomeTwoToneIcon from '@mui/icons-material/HomeTwoTone';
import ShowChartTwoToneIcon from '@mui/icons-material/ShowChartTwoTone';
import AutoFixHighTwoToneIcon from '@mui/icons-material/AutoFixHighTwoTone';
import InfoTwoToneIcon from '@mui/icons-material/InfoTwoTone';
import ArrowDropDownRoundedIcon from '@mui/icons-material/ArrowDropDownRounded';
import ArrowDropUpRoundedIcon from '@mui/icons-material/ArrowDropUpRounded';
import MenuTwoToneIcon from '@mui/icons-material/MenuTwoTone';
import CloseTwoToneIcon from '@mui/icons-material/CloseTwoTone';
import TipsAndUpdatesTwoToneIcon from '@mui/icons-material/TipsAndUpdatesTwoTone';
import FmdGoodTwoToneIcon from '@mui/icons-material/FmdGoodTwoTone';
import PeopleAltTwoToneIcon from '@mui/icons-material/PeopleAltTwoTone';

export const HomeIcon = HomeTwoToneIcon;
export const CareerIcon = ShowChartTwoToneIcon;
export const FeatureIcon = AutoFixHighTwoToneIcon;
export const AboutusIcon = InfoTwoToneIcon;
export const DropdownIcon = ArrowDropDownRoundedIcon;
export const DropupIcon = ArrowDropUpRoundedIcon;
export const MenuIcon = MenuTwoToneIcon;
export const CloseIcon = CloseTwoToneIcon;
export const BulbIcon = TipsAndUpdatesTwoToneIcon;
export const LocationIcon = FmdGoodTwoToneIcon;
export const PeopleIcon= PeopleAltTwoToneIcon;